---
#
# Installing npm
#

# Installing npm

- name: Install Dependency
  apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
  with_items:
    - 'nodejs'
    - 'npm'

- name: Setting Elasticsearch to run on boot
  shell: 'npm install elastic-apm-node --save'

- name: Success Message
  debug:
    msg: "Installed npm and nodejs"
