---
#
# Installing Kibana
#

# Install Kibana

# APT - Advanced Package Tool, or APT, is a free software user interface that
# works with core libraries to handle the installation and removal of
# software on Debian, Ubuntu and other Linux distributions

# Add the Elasticsearch apt repo. For versions 6 of the stack - use '6.x-prerelease':

- name: echo
  shell: 'wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -'

- name: update
  shell: 'echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-6.x.list'

- name: Install Kibana with apt
  apt:
   name: kibana
   update_cache: yes

# Configurations

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/kibana/kibana.yml # path of the file
   regexp: 'server.host:' # The regular expression to look for in every line of the file
   line: 'server.host: 0.0.0.0'  # The line to insert/replace into the file

# Starting Kibana

- name: Starting Kibana
  service:
   name: kibana
   state: started

- name: Setting Kibana to run on boot
  shell: 'sudo update-rc.d kibana defaults 96 9'

- name: Success Message
  debug:
    msg: "Kibana running sucessfully"
