---
#
# Installing Kibana
#

# Install Kibana

# APT - Advanced Package Tool, or APT, is a free software user interface that
# works with core libraries to handle the installation and removal of
# software on Debian, Ubuntu and other Linux distributions

# Add the Elasticsearch apt repo. For versions 6 of the stack - use '6.x-prerelease':


- name: echo
  shell: 'echo "deb http://packages.elastic.co/kibana/4.5/debian stable main" | sudo tee -a /etc/apt/sources.list.d/kibana-4.5.x.list'

- name: update
  shell: 'sudo apt-get update'

- name: Install
  shell: 'sudo apt-get -y install kibana'

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/kibana/kibana.yml # path of the file
   regexp: 'server.host:' # The regular expression to look for in every line of the file
   line: 'server.host: 0.0.0.0'  # The line to insert/replace into the file

- name: defaults
  shell: 'sudo update-rc.d kibana defaults 96 9'

- name: start
  shell: 'sudo service kibana start'




# - name: Downloading Kibana
#   apt:
#    deb: "https://artifacts.elastic.co/downloads/kibana/kibana-6.3.2-amd64.deb"
#    state: present
#
# - name: Install Kibana with apt
#   apt:
#    name: kibana
#    update_cache: yes
#
# # Configurations
#
# - name: Updating the config file to allow outside access
#   lineinfile:
#    destfile: /etc/kibana/kibana.yml # path of the file
#    regexp: 'server.host:' # The regular expression to look for in every line of the file
#    line: 'server.host: 0.0.0.0'  # The line to insert/replace into the file
#
# - name: Defining server port
#   lineinfile:
#    destfile: /etc/kibana/kibana.yml
#    regexp: 'server.port:'
#    line: 'server.port: 5601'
#
# # - name: Install xpack
# #   shell: 'cd /usr/share/kibana && sudo bin/kibana-plugin install x-pack'
#
# - name: Disable xpack
#   lineinfile:
#    destfile: /etc/kibana/kibana.yml
#    regexp: 'xpack.security.enabled:'
#    line: 'xpack.security.enabled: false'
#
# # - name: Defining server username
# #   lineinfile:
# #    destfile: /etc/kibana/kibana.yml
# #    regexp: 'elasticsearch.username:'
# #    line: '#elasticsearch.username: "kibana"'
# #
# # - name: Defining server password
# #   lineinfile:
# #    destfile: /etc/kibana/kibana.yml
# #    regexp: 'elasticsearch.password:'
# #    line: '#elasticsearch.password: "kibana"'
# #
# # - name: Defining kibana_version
# #   lineinfile:
# #    destfile: /etc/kibana/kibana.yml
# #    regexp: 'kibana_version:'
# #    line: 'kibana_version: "4.6"'
#
#    #elasticsearch.username: "user"
#    #elasticsearch.password: "pass"
# - name: Start Process - Kibana
#   shell: sudo update-rc.d kibana defaults 96 9
#
# # Starting Kibana
#
# - name: Starting Kibana
#   service:
#    name: kibana
#    state: started
