---
#
# Installing Elasticsearch
#

- name: echo
  shell: 'wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -'

- name: update
  shell: 'echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-6.x.list'

# Installing Elasticsearch

- name: Install Elasticsearch
  apt:
   name: elasticsearch
   update_cache: yes

# Update Elasticsearch config file to allow access (to secure Elasticsearch, bind to 'localhost').

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'network.host:'
   line: 'network.host: 0.0.0.0'

# Start Elasticsearch

- name: Starting Elasticsearch
  service:
   name: elasticsearch
   state: restarted

- name: Setting Elasticsearch to run on boot
  shell: 'sudo update-rc.d elasticsearch defaults 95 10'

- name: Success Message
  debug:
    msg: "Elasticsearch running sucessfully"
