---
#
# Installing apm-server
#

# Install apm-server

# APT - Advanced Package Tool, or APT, is a free software user interface that
# works with core libraries to handle the installation and removal of
# software on Debian, Ubuntu and other Linux distributions

- name: echo
  shell: 'wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -'

# - name: Installing
#   shell: 'sudo apt-get update'

- name: update
  shell: 'echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-6.x.list'

- name: update
  shell: 'sudo apt-get update'

  #setup.dashboards.enabled: false
    #host: "localhost:5601

# - name: Install Kibana with apt
#   apt:
#    name: kibana
#    update_cache: yes

- name: Install
  shell: 'sudo apt-get -y install apm-server'

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/apm-server/apm-server.yml # path of the file
   regexp: '#host: "localhost:5601"' # The regular expression to look for in every line of the file
   line: 'host: "localhost:5601"'  # The line to insert/replace into the file

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/apm-server/apm-server.yml # path of the file
   regexp: 'setup.dashboards.enabled:' # The regular expression to look for in every line of the file
   line: 'setup.dashboards.enabled: true'  # The line to insert/replace into the file

- name: defaults
  shell: 'sudo update-rc.d apm-server defaults 95 10'

- name: start
  shell: 'sudo service apm-server start'
