---
#
# Installing apm-server
#

# Install apm-server

# APT - Advanced Package Tool, or APT, is a free software user interface that
# works with core libraries to handle the installation and removal of
# software on Debian, Ubuntu and other Linux distributions

- name: echo
  shell: 'wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -'

# - name: Installing
#   shell: 'sudo apt-get update'

- name: update
  shell: 'echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-6.x.list'

- name: update
  shell: 'sudo apt-get update'

# - name: Install Kibana with apt
#   apt:
#    name: kibana
#    update_cache: yes

- name: Install
  shell: 'sudo apt-get -y install apm-server'

- name: defaults
  shell: 'sudo update-rc.d apm-server defaults 95 10'

- name: start
  shell: 'sudo service apm-server start'
